backend:
  name: github
  repo: meirelescafe/andersonmeireles-site
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

locale: 'pt'

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "DD/MM/YYYY", timeFormat: false }
      - { label: "Capa do post", name: "thumbnail", widget: "image", required: false }
      - { label: "Resumo", name: "summary", widget: "text", hint: "Aparece no card do blog (máx. 200 caracteres)" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
